name: esther_math_app
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.11.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  cloud_firestore: ^4.12.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  uuid: ^4.2.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true




